services:
  api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    ports:
      - "9000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis://redis:6379
      - ConnectionStrings__Postgres=Host=postgres;Database=taskmanager;Username=postgres;Password=postgres
      - ConnectionStrings__EventStore=esdb://eventstore:2113?tls=false
    depends_on:
      - postgres
      - redis
      - eventstore

  redis:
    image: redislabs/rejson:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "9010:5540"
    volumes:
      - redis-insight-data:/db

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  eventstore:
    image: eventstore/eventstore:22.10.1-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - eventstore-data:/var/lib/eventstore

volumes:
  redis-data:
  redis-insight-data:
  postgres-data:
  eventstore-data: